apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-blog
  template:
    metadata:
      labels:
        app: api-blog
    spec:
      containers:
        - name: app-api
          image: fastapi-docker
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 8000